name: Sitoproxy Auto Bot
on:
  schedule:
    - cron: '14 * * * *' # اجرای خودکار در دقیقه ۱۴ هر ساعت (پایدارتر و بدون تداخل)
  workflow_dispatch: # دکمه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Run Proxy Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
